---
title: "Resources"
---
## Jobs Board
```{=html}
<div style="display: flex; justify-content: top; align-items: center; width: 800px; height: 400px;">
    <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSVUG4pJ3XeyhnJ9AT7lphmw_P_1mIJ7Man_nqf2zfE4uEcrybaLLMAR_LFRsDnfvWX_CdkUt8CnZF7/pubhtml?gid=0&amp;single=true&amp;widget=false&amp;headers=false&amp;chrome=false" title="Webpage example" style="width: 100%; height: 100%;"></iframe>
</div>
```

## Books
| **_Author/Owner_** 	| **_Title_**                                                                    	| PyData 2023 Sponsor? 	| **_Description_**                                                 	|
|--------------------	|--------------------------------------------------------------------------------	|----------------------	|-------------------------------------------------------------------	|
| O'Reilly           	| [Gen AI resources](https://www.oreilly.com/online-learning/generative-ai.html) 	| True                 	| A collection of resources available through the learning platform 	|
| O'Reilly           	| [Open Books](https://www.oreilly.com/openbook/)                                	| True                 	| Books with open copyright                                         	|
| Launch School      	| [Introduction to Programming with Python](https://launchschool.com/books/python)   |                 	|                             	|
| Launch School      	| [Object Oriented Programming with Python](https://launchschool.com/books/oo_python)   |                 	|                           	|

## Free Courses
| **_Author/Owner_** 	| **_Description_**                                                                                                              	| PyData 2023 Sponsor? 	| PyData 2024 Meetup Sponsor? 	|
|--------------------	|--------------------------------------------------------------------------------------------------------------------------------	|----------------------	|-----------------------------	|
| Microsoft          	| [Microsoft Azure AI Fundamentals: Generative AI](https://learn.microsoft.com/en-us/training/paths/introduction-generative-ai/) 	| True                 	|                             	|
| Microsoft          	| [AI Learning Hub](https://learn.microsoft.com/en-us/ai/)                                                                       	| True                 	|                             	|
| Google             	| [Generative AI for Developers Learning Path](https://www.cloudskillsboost.google/paths/183)                                    	| True                 	|                             	|
| Google             	| [Introduction to Generative AI Learning Path](https://www.cloudskillsboost.google/paths/118)                                   	| True                 	|                             	|
| IBM                	| [Generative AI for Developers](https://developer.ibm.com/generative-ai-for-developers?cm_sp=ibmdev--developer--GenAI)          	|                      	| True                        	|

## Learning Platforms (Paid)
| **_Author/Owner_** 	| **_Description_**           | 
|--------------------	|----------------------------------- |
| Packt       | [Packt Platform](https://www.packtpub.com/) 	| 
| Pearson    	| [PearsonPlus](https://www.pearson.com/en-us/pearsonplus.html) | 
| O'Reilly   	| [O'Reilly Online Learning Platform](https://www.oreilly.com/online-learning/) | 